"use strict";

const shuffle = function (arr) {
  let arrCp = arr.slice();
  let length = arrCp.length;

  while (length) {
    // 랜덤한 배열 index 추출
    let index = Math.floor(length-- * Math.random());

    // 배열의 끝에서부터 0번째 아이템을 순차적으로 대입
    let temp = arrCp[length];

    // 랜덤한 위치의 값을 맨뒤(arrCp[length])부터 셋팅
    arrCp[length] = arrCp[index];

    // 랜덤한 위치에 위에 설정한 temp값 셋팅
    arrCp[index] = temp;
  }

  return arrCp;
};

const drawingsMockup = [
  {
    title: "내가 갖고 싶은 눈",
    DrawingImg: "image01.jpeg",
    description:
      "일주일 내내 그려서 겨우 완성! 결과물이 좀 나와서 뿌듯합니당 ^^",
    isCompleted: true,
    Users_id: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "아름답지만 독기품은 꽃",
    DrawingImg: "image02.jpg",
    description: "이제 2주 지났는데...힘들어요ㅠ 끝까지 화이팅!",
    isCompleted: true,
    Users_id: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "화려하지만 시들어가는 꽃",
    DrawingImg: "image03.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "정물화의 정수",
    DrawingImg: "image04.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "천지창조를 보고 영감을 얻어 그림",
    DrawingImg: "image05.jpg",
    description: "",
    isCompleted: true,
    Users_id: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "거울보고 그림",
    DrawingImg: "image06.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "스카이캐슬",
    DrawingImg: "image07.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "내 마음가는대로",
    DrawingImg: "image08.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "세로의 미학",
    DrawingImg: "image09.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "숲속의 새",
    DrawingImg: "image10.jpg",
    description: "",
    isCompleted: true,
    Users_id: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "사우론의 눈",
    DrawingImg: "image11.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "난을 쳐보았습니다.",
    DrawingImg: "image12.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "화려한 정물화",
    DrawingImg: "image13.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "삼형제",
    DrawingImg: "image14.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "물감을 무질서하게",
    DrawingImg: "image15.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "마돈나를 내 느낌대로",
    DrawingImg: "image16.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "내가 바로 김홍도",
    DrawingImg: "image17.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "꽃밭에 앉은 소녀",
    DrawingImg: "image18.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "비온 뒤 맑음",
    DrawingImg: "image19.jpg",
    description: "",
    isCompleted: true,
    Users_id: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "블랙 오마주",
    DrawingImg: "image20.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "샌프란시스코",
    DrawingImg: "image21.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "1940년대 연인",
    DrawingImg: "image22.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "아이언맨 집",
    DrawingImg: "image23.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "SCHEVENINGEN",
    DrawingImg: "image24.jpg",
    description: "",
    isCompleted: true,
    Users_id: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "월-E",
    DrawingImg: "image25.jpg",
    description: "",
    isCompleted: true,
    Users_id: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "가을 숲",
    DrawingImg: "image26.jpg",
    description: "",
    isCompleted: true,
    Users_id: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "라퓨타 배경",
    DrawingImg: "image27.jpg",
    description: "",
    isCompleted: true,
    Users_id: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "시골 아담한 풍경",
    DrawingImg: "image28.jpg",
    description: "",
    isCompleted: true,
    Users_id: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "해변가",
    DrawingImg: "image29.jpg",
    description: "",
    isCompleted: true,
    Users_id: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "도심속 숲",
    DrawingImg: "image31.jpg",
    description: "",
    isCompleted: true,
    Users_id: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "천공의 섬",
    DrawingImg: "image30.jpg",
    description: "",
    isCompleted: true,
    Users_id: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "아이유",
    DrawingImg: "image32.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "바닷속 영롱",
    DrawingImg: "image33.jpg",
    description: "",
    isCompleted: true,
    Users_id: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "히말라야에서의 은하",
    DrawingImg: "image34.jpg",
    description: "",
    isCompleted: true,
    Users_id: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "가을 공원",
    DrawingImg: "image35.jpg",
    description: "",
    isCompleted: true,
    Users_id: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "가면속 여자",
    DrawingImg: "image36.jpg",
    description: "",
    isCompleted: true,
    Users_id: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "아포칼립스",
    DrawingImg: "image37.jpg",
    description: "",
    isCompleted: true,
    Users_id: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "사이버 소녀",
    DrawingImg: "image38.jpg",
    description: "",
    isCompleted: true,
    Users_id: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "라오스의 어느 해변가",
    DrawingImg: "image39.jpg",
    description: "",
    isCompleted: true,
    Users_id: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "별의 궤적",
    DrawingImg: "image40.jpg",
    description: "",
    isCompleted: true,
    Users_id: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "몽환적인 폭포",
    DrawingImg: "image41.jpg",
    description: "",
    isCompleted: true,
    Users_id: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "벚꽃휘날리며",
    DrawingImg: "image42.jpg",
    description: "",
    isCompleted: true,
    Users_id: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "노을아래 도심",
    DrawingImg: "image43.jpg",
    description: "",
    isCompleted: true,
    Users_id: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "백조의 호수",
    DrawingImg: "image44.jpg",
    description: "",
    isCompleted: true,
    Users_id: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "노르웨이의 숲",
    DrawingImg: "image45.jpg",
    description: "",
    isCompleted: true,
    Users_id: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "그림그리는 내모습",
    DrawingImg: "image46.jpg",
    description: "",
    isCompleted: true,
    Users_id: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "해변가 도로",
    DrawingImg: "image47.jpg",
    description: "",
    isCompleted: true,
    Users_id: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "블랙오션",
    DrawingImg: "image48.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "동물들의 영화나들이",
    DrawingImg: "image49.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "혼돈",
    DrawingImg: "image50.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "백작 인물화",
    DrawingImg: "image51.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "그윽한 눈빛의 여인",
    DrawingImg: "image52.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "상상속의 동물",
    DrawingImg: "image53.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "참새 5마리",
    DrawingImg: "image54.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "용암",
    DrawingImg: "image55.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "스페인의 여인",
    DrawingImg: "image57.jpeg",
    description: "",
    isCompleted: true,
    Users_id: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const drawingData = shuffle(drawingsMockup);

module.exports = {
  up: async (queryInterface, Sequelize) => {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
    return queryInterface.bulkInsert("Drawings", drawingData);
  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    return queryInterface.bulkDelete("Drawings", null, {});
  },
};
